feat: add lido

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -1802,14 +1802,16 @@ query_deployment() {
       "rpc" "Ethereum RPC node - consensus and execution client" 3>&1 1>&2 2>&3)
     elif uname -a | grep -q aarch64; then
       __deployment=$(whiptail --notags --title "Select deployment type" --menu \
-      "What kind of deployment do you want to run?" 11 80 4 \
+      "What kind of deployment do you want to run?" 11 80 5 \
       "node" "Ethereum node - consensus, execution and validator client" \
+      "lido" "[LIDO] Nodes, validator client, generated keys for Lido Community Staking" \
       "rocket" "Validator client only - integrate with RocketPool" \
       "rpc" "Ethereum RPC node - consensus and execution client" 3>&1 1>&2 2>&3)
     else
       __deployment=$(whiptail --notags --title "Select deployment type" --menu \
-      "What kind of deployment do you want to run?" 12 80 5 \
+      "What kind of deployment do you want to run?" 12 80 6 \
       "node" "Ethereum node - consensus, execution and validator client" \
+      "lido" "[LIDO] Nodes, validator client, generated keys for Lido Community Staking" \
       "rocket" "Validator client only - integrate with RocketPool" \
       "ssv" "SSV node - consensus, execution and ssv-node" \
       "rpc" "Ethereum RPC node - consensus and execution client" 3>&1 1>&2 2>&3)
@@ -2129,7 +2131,16 @@ query_coinbase() {
     FEE_RECIPIENT=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
 
     while true; do
-        if [ "${__deployment}" = rpc ]; then
+        if [ "${__deployment}" = lido ]; then
+            case "${NETWORK}" in
+                "goerli")
+                    FEE_RECIPIENT="0x94750381be1aba0504c666ee1db118f68f0780d4"
+                    ;;
+                "mainnet")
+                    FEE_RECIPIENT="0x388c818ca8b9251b393131c08a736a67ccb19297"
+                    ;;
+            esac
+        elif [ "${__deployment}" = rpc ]; then
             FEE_RECIPIENT=$(whiptail --title "Configure fee recipient" --inputbox "What is the fallback fee recipient address? Yes even on an RPC node. Can be any address at all. (right-click to paste, CANNOT be an ENS)" 10 60 "${FEE_RECIPIENT}" 3>&1 1>&2 2>&3)
         else
             FEE_RECIPIENT=$(whiptail --title "Configure rewards address" --inputbox "What is the address you want transaction rewards to be sent to by default? (right-click to paste, CANNOT be an ENS)" 10 60 "${FEE_RECIPIENT}" 3>&1 1>&2 2>&3)
@@ -2198,7 +2209,68 @@ https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1e
     value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
     if (whiptail --title "MEV Boost" --yesno "Do you want to use MEV Boost?" 10 60) then
         MEV_BOOST="true"
-        if [ "${value}" = "true" ]; then
+        if [ "${__deployment}" = lido ]; then
+            MEV_RELAYS=""
+            __selected=""
+            declare -A relays=()
+            case "${NETWORK}" in
+                "goerli")
+                    __selected=$(whiptail --title "Relays list" --checklist \
+                        "Choose desired relays" 15 30 6 \
+                        "Flashbots" "" ON \
+                        "Blocknative" "" ON \
+                        "Bloxroute" "" ON \
+                        "Edennetwork" "" ON \
+                        "Securerpc" "" ON \
+                        "Ultrasound" "" ON 3>&1 1>&2 2>&3)
+                    relays=(
+                        ['Flashbots']="https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@builder-relay-goerli.flashbots.net"
+                        ['Blocknative']="https://0x8f7b17a74569b7a57e9bdafd2e159380759f5dc3ccbd4bf600414147e8c4e1dc6ebada83c0139ac15850eb6c975e82d0@builder-relay-goerli.blocknative.com"
+                        ['Bloxroute']="https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.max-profit.builder.goerli.blxrbdn.com"
+                        ['Edennetwork']="https://0xaa1488eae4b06a1fff840a2b6db167afc520758dc2c8af0dfb57037954df3431b747e2f900fe8805f05d635e9a29717b@relay-goerli.edennetwork.io"
+                        ['Securerpc']="https://0x8a72a5ec3e2909fff931c8b42c9e0e6c6e660ac48a98016777fc63a73316b3ffb5c622495106277f8dbcc17a06e92ca3@goerli-relay.securerpc.com"
+                        ['Ultrasound']="https://0xb1559beef7b5ba3127485bbbb090362d9f497ba64e177ee2c8e7db74746306efad687f2cf8574e38d70067d40ef136dc@relay-stag.ultrasound.money"
+                    )
+                    ;;
+                "mainnet")
+                    __selected=$(whiptail --title "Relays list" --checklist \
+                        "Choose desired relays" 15 40 9 \
+                        "Blocknative" "" ON \
+                        "Bloxroute (regulated)" "" ON \
+                        "Bloxroute (max profit)" "" ON \
+                        "Aestus" "" ON \
+                        "Flashbots" "" ON \
+                        "Edennetwork" "" ON \
+                        "Securerpc" "" ON \
+                        "Ultrasound" "" ON \
+                        "Agnostic" "" ON 3>&1 1>&2 2>&3)
+                    relays=(
+                        ["Blocknative"]="https://0x9000009807ed12c1f08bf4e81c6da3ba8e3fc3d953898ce0102433094e5f22f21102ec057841fcb81978ed1ea0fa8246@builder-relay-mainnet.blocknative.com"
+                        ["Bloxroute (regulated)"]="https://0xb0b07cd0abef743db4260b0ed50619cf6ad4d82064cb4fbec9d3ec530f7c5e6793d9f286c4e082c0244ffb9f2658fe88@bloxroute.regulated.blxrbdn.com"
+                        ["Bloxroute (max profit)"]="https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com"
+                        ["Aestus"]="https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live"
+                        ["Flashbots"]="https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.nett"
+                        ["Edennetwork"]="https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io"
+                        ["Securerpc"]="https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com"
+                        ["Ultrasound"]="https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money"
+                        ["Agnostic"]="https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net"
+                    )
+                    ;;
+                  *)
+                    echo "Invalid network"
+                    exit 1
+                    ;;
+            esac
+            for i in "${!relays[@]}"; do
+                if [[ ${__selected} =~ ${i} ]]; then
+                    if [ -z "${MEV_RELAYS}" ]; then
+                        MEV_RELAYS="${relays[$i]}"
+                    else
+                        MEV_RELAYS="${MEV_RELAYS},${relays[$i]}"
+                    fi
+                fi
+            done
+        elif [ "${value}" = "true" ]; then
             var="MEV_RELAYS"
             MEV_RELAYS=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
         else
@@ -2233,7 +2305,9 @@ https://0x8c7d33605ecef85403f8b7289c8058f440cbb6bf72b055dfe2f3e2c6695b6a1ea5a9cd
                     ;;
             esac
         fi
-        MEV_RELAYS=$(whiptail --title "Configure MEV relays" --inputbox "What MEV relay(s) do you want to use? (right-click to paste)" 10 60 "${MEV_RELAYS}" 3>&1 1>&2 2>&3)
+        if [ ! "${__deployment}" = lido ]; then
+            MEV_RELAYS=$(whiptail --title "Configure MEV relays" --inputbox "What MEV relay(s) do you want to use? (right-click to paste)" 10 60 "${MEV_RELAYS}" 3>&1 1>&2 2>&3)
+        fi
 
         exitstatus=$?
         if [ $exitstatus -eq 0 ]; then
@@ -2246,6 +2320,39 @@ https://0x8c7d33605ecef85403f8b7289c8058f440cbb6bf72b055dfe2f3e2c6695b6a1ea5a9cd
         MEV_BOOST="false"
         MEV_RELAYS=""
     fi
+}
+
+query_lido_keys_generation() {
+    __num_validators="1"
+    __keystore_password=""
+    __num_validators=$(whiptail --title "Validators count" --inputbox "Enter the number of validators" 8 60 "${__num_validators}" 3>&1 1>&2 2>&3)
+    __keystore_password=$(whiptail --title "Keystore password" --passwordbox "Enter validators keystore password" 8 60 "${__keystore_password}" 3>&1 1>&2 2>&3)
+
+    case "${NETWORK}" in
+        "goerli")
+            __execution_address="0x94750381bE1AbA0504C666ee1DB118F68f0780D4"
+            ;;
+        "mainnet")
+            __execution_address="0xB9D7934878B5FB9610B3fE8A5e441e8fad7E293f"
+            ;;
+        *)
+            __execution_address="0x0000000000000000000000000000000000000000"
+            ;;
+    esac
+
+
+    exitstatus=$?
+    if [ $exitstatus -eq 0 ]; then
+        echo "your Number of validators is:" "${__num_validators}"
+        EXECUTION_ADDRESS=${__execution_address} KEYSTORE_PASSWORD=${__keystore_password} NUM_VALIDATORS=${__num_validators} docompose -f ./lido-deposit-cli.yml run --rm deposit-cli-new
+    else
+        echo "You chose Cancel."
+        exit 1
+    fi
+}
+
+query_lido_redirect_to_submission() {
+    whiptail --title "Finish" --msgbox "Final steps!\n\n1. Please, open https://operators.lido.fi to submit your keys\n\n2. Wait for keys validation\n\n3. Run your nodes by './ethd start'\n\n4. Import your keys by './ethd keys import'" 15 85
 }
 
 set_value_in_env() {
@@ -2286,7 +2393,7 @@ config() {
     query_network
     query_deployment
     case "${__deployment}" in
-      "node")
+      "node" | "lido")
         query_consensus_client
         ;;
       "validator" | "rocket")
@@ -2330,6 +2437,12 @@ config() {
         if [ "${__deployment}" = "node" ]; then
           query_graffiti
         fi
+        if [ "${__deployment}" = "lido" ]; then
+          if (whiptail --title "Keys generation" --yesno "Do you want to generate validator keys?" 10 60) then
+            query_lido_keys_generation
+          fi
+          query_lido_redirect_to_submission
+        fi
     else
         unset EXECUTION_CLIENT
         unset GRAFANA_CLIENT
@@ -2355,7 +2468,9 @@ config() {
     if [ "${MEV_BOOST}" = "true" ]; then
         COMPOSE_FILE="${COMPOSE_FILE}:mev-boost.yml"
     fi
-    if [ "${NETWORK}" = "goerli" ] || [ "${NETWORK}" = "zhejiang" ]; then
+    if [ ! "${__deployment}" = "lido" ]; then
+        COMPOSE_FILE="${COMPOSE_FILE}:lido-deposit-cli.yml"
+    elif [ "${NETWORK}" = "goerli" ] || [ "${NETWORK}" = "zhejiang" ]; then
         COMPOSE_FILE="${COMPOSE_FILE}:deposit-cli.yml"
     fi
 # Not multi-arch, this would break on ARM64
